import './globals.css';
import QueryProvider from '@/providers/QueryProvider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} min-h-screen flex flex-col relative`}>
        <div className="bg-gray-100">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
